
--- CREATION
CREATE TABLE CONSOTELPERIOD AS
SELECT  NCLI,
        NOTEL,
        TRUNC(DATEHEURE) AS DATEJOUR,
        SUM(DUREE) AS DUREEPERIODE,
        MAX(DUREE) AS DUREEMAX,
        MIN(DUREE) AS DUREEMIN,
        AVG(DUREE) AS DUREEMOY,
        COUNT(*) AS APPEL_PAR_PERIODE,
        1+TRUNC((CONSOTEL.DATEHEURE-TRUNC(CONSOTEL.DATEHEURE,'DD'))*24/6) AS PERIODE
        FROM CONSOTEL
        GROUP BY NCLI,NOTEL,TRUNC(DATEHEURE),1+TRUNC((CONSOTEL.DATEHEURE -TRUNC(CONSOTEL.DATEHEURE,'DD'))*24/6);
        
SELECT * FROM CONSOTELPERIOD; --102 LIGNES

SELECT TO_CHAR(DATEJOUR,'DAY'),PERIODE,SUM(APPEL_PAR_PERIODE),SUM(DUREEPERIODE),MAX(DUREEMAX),AVG(DUREEMOY)
FROM CONSOTELPERIOD 
GROUP BY TO_CHAR(DATEJOUR, 'DAY'),PERIODE
ORDER BY TO_CHAR(DATEJOUR, 'D');


SELECT to_char(to_date(DATEJOUR), 'IW') AS NUMERO_SEMAINE,
SUM(APPEL_PAR_PERIODE),
SUM(DUREEPERIODE)
FROM CONSOTELPERIOD 
GROUP BY to_char(to_date(DATEJOUR), 'IW');-- 4 LIGNES


SELECT TO_CHAR(j.DATEJOUR, 'DAY'), j.DUREEMAX
FROM  CONSOTELPERIOD j
WHERE j.DUREEMAX=(select  MAX(t.DUREEMAX)
                from  CONSOTELPERIOD t
                where TO_CHAR(t.DATEJOUR, 'DAY')=TO_CHAR(t.DATEJOUR, 'DAY')
);--LUNDI

SELECT TO_CHAR(j.DATEJOUR, 'DAY') AS JOUR_SEMAINE, PERIODE, MAX(j.DUREEMAX)
FROM  CONSOTELPERIOD j
GROUP BY  TO_CHAR(j.DATEJOUR, 'DAY'),PERIODE,j.DUREEMAX; --71 LIGNES